### PR TITLE
Unify `pbench-fio`'s use of `screen`

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Review by dbutenhof — APPROVED** [review]
I like that refactoring.

**Review by webbnh — APPROVED** [review]
I like this very much.

But, I feel compelled to point out that I don't think it will work if `${benchmark_bin}` or `${benchmark_results_dir}` have any funky filenames in their respective paths.

Is that something we have to defend against?

**Review by webbnh — APPROVED** [review]
GTG

**Comment by portante** [comment]
Merged independently of GitHub.

**Pull request closed without merging**
